- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    project: 'C:\Users\MKU\Desktop\fixed\HOMIE-soapui-project.xml'
    rootFolder: '$(Common.TestResultsDirectory)'
    testSuite: 'TestRunner'
    testCase: 'TestRunner'