# Starter pipeline
- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    testRunnerPath: 'C:\Users\MKU\AppData\Local\SmartBear\SoapUI-5.6.0\bin\TestRunner.bat'
    project: 'C:\Users\MKU\Desktop\fixed\HOMIE-soapui-project.xml'
    rootFolder: '$(Common.TestResultsDirectory)'
    testSuite: 'TestRunner'
    testCase: 'TestRunner'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more
# https://aka.ms/yaml

trigger:
- 
main
pool:
- task: SoapUIProForAzureDevOpsTask@2
  inputs:
    project: 'C:\Users\MKU\Desktop\fixed\HOMIE-soapui-project.xml'
    rootFolder: '$(Common.TestResultsDirectory)'
    testSuite: 'TestRunner'
    testCase: 'TestRunner'
    vmImage: ubuntu-latest
steps:
-script: echo Hello, world!
    displayName: 'Run a one-line script'
-script:
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'